#!/bin/bash
# Step-by-step guide to add Python to Screen Recording permissions

clear

echo "╔══════════════════════════════════════════════════════════════════╗"
echo "║  🔓 Adding Python to Screen Recording Permissions               ║"
echo "║                                                                  ║"
echo "║  Follow along - I'll open everything for you!                   ║"
echo "╚══════════════════════════════════════════════════════════════════╝"
echo ""
sleep 2

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📂 STEP 1: Opening System Preferences..."
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# Open System Preferences to Screen Recording
echo "   Opening: Security & Privacy → Screen Recording"
echo ""

# Try the direct URL approach
open "x-apple.systempreferences:com.apple.preference.security?Privacy_ScreenCapture"

sleep 3

echo "   ✅ System Preferences should now be open"
echo ""
sleep 1

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🔓 STEP 2: Unlock Settings (if locked)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "   👀 Look at the bottom-left corner of the window"
echo ""
echo "   Do you see a 🔒 LOCK icon?"
echo ""
echo "   If YES:"
echo "      1. Click the 🔒 lock icon"
echo "      2. Enter your Mac password"
echo "      3. The lock will change to 🔓 (unlocked)"
echo ""
echo "   If the lock is already 🔓 (unlocked), skip this step!"
echo ""

read -p "   Press ENTER when the settings are unlocked (🔓)..."
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "➕ STEP 3: Add Python to the list"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "   👀 Look at the list of apps on the right side"
echo ""
echo "   You should see:"
echo "      ☑️  Terminal  (already checked)"
echo ""
echo "   Now we need to add Python:"
echo ""
echo "   1. Look BELOW the app list"
echo "   2. Find the ➕ (plus) button"
echo "   3. Click the ➕ button"
echo ""
echo "   A file browser window will open"
echo ""

read -p "   Press ENTER after clicking the ➕ button..."
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🔍 STEP 4: Navigate to Python"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "   The file browser is now open. Follow these steps:"
echo ""
echo "   1. Press: Cmd + Shift + G  (all at the same time)"
echo "      This opens 'Go to folder'"
echo ""
echo "   2. A text box will appear at the top"
echo ""
echo "   3. Type exactly:  /usr/bin"
echo ""
echo "   4. Press ENTER"
echo ""

read -p "   Press ENTER after typing /usr/bin and pressing ENTER..."
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📍 STEP 5: Find and select python3"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "   You should now see a HUGE list of files in /usr/bin"
echo ""
echo "   Method 1: Search for python3"
echo "      1. Click in the file list"
echo "      2. Type: python3"
echo "      3. It should jump to files starting with 'python'"
echo ""
echo "   Method 2: Scroll manually"
echo "      1. Scroll down in the list"
echo "      2. Look for 'python3' (it's alphabetical)"
echo ""
echo "   When you find 'python3':"
echo "      1. Click on it ONCE (it will highlight)"
echo "      2. Click the 'Open' button (bottom-right)"
echo ""

read -p "   Press ENTER after selecting python3 and clicking Open..."
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "✅ STEP 6: Verify python3 was added"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "   You should now see in the app list:"
echo ""
echo "      ☑️  Terminal"
echo "      ☑️  python3"
echo ""
echo "   MAKE SURE BOTH BOXES ARE CHECKED!"
echo ""
echo "   If python3's box is NOT checked:"
echo "      Click on the checkbox next to python3"
echo ""

read -p "   Press ENTER when BOTH boxes are checked..."
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🔒 STEP 7: Lock settings and close"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "   1. Click the 🔓 lock icon (bottom-left) to lock it again"
echo "   2. Close System Preferences window (click the red ❌)"
echo ""

read -p "   Press ENTER after closing System Preferences..."
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🔄 STEP 8: RESTART Terminal (CRITICAL!)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "   ⚠️  This is the MOST IMPORTANT step!"
echo ""
echo "   You MUST quit Terminal completely:"
echo ""
echo "   Method 1: Keyboard shortcut (recommended)"
echo "      Press: Cmd + Q"
echo ""
echo "   Method 2: Menu"
echo "      Click: Terminal menu → Quit Terminal"
echo ""
echo "   ❌ DON'T just close the window!"
echo "   ✅ You must QUIT the entire app!"
echo ""
echo "   After quitting:"
echo "      1. Wait 3 seconds"
echo "      2. Open Terminal again (from Applications → Utilities)"
echo "      3. cd /Users/djrussell23/Documents/repos/Ironcliw-AI-Agent"
echo "      4. python3 check_screen_recording_permission.py"
echo ""

read -p "   Press ENTER, then quit Terminal (Cmd+Q)..."
echo ""

echo "╔══════════════════════════════════════════════════════════════════╗"
echo "║  ✅ Setup Complete!                                              ║"
echo "║                                                                  ║"
echo "║  Now:                                                            ║"
echo "║    1. Quit Terminal (Cmd+Q)                                      ║"
echo "║    2. Reopen Terminal                                            ║"
echo "║    3. cd to Ironcliw-AI-Agent folder                               ║"
echo "║    4. Run: python3 check_screen_recording_permission.py          ║"
echo "║                                                                  ║"
echo "║  You should see: ✅ Screen Recording permission is GRANTED       ║"
echo "╚══════════════════════════════════════════════════════════════════╝"
echo ""
