#!/bin/bash
# Alternative approach: Reset and re-grant Screen Recording permission

echo "╔══════════════════════════════════════════════════════════════════╗"
echo "║  🔧 Alternative Permission Fix                                   ║"
echo "╚══════════════════════════════════════════════════════════════════╝"
echo ""

echo "Since /usr/bin/python3 is hard to find in the file browser,"
echo "let's try a different approach:"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Option 1: Reset Screen Recording permissions (Recommended)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "This will reset Terminal's Screen Recording permission"
echo "so macOS asks you again (fresh start):"
echo ""
echo "Run this command:"
echo ""
echo "sudo tccutil reset ScreenCapture com.apple.Terminal"
echo ""
read -p "Run this command? (y/n): " RESET_CHOICE

if [[ "$RESET_CHOICE" == "y" ]]; then
    echo ""
    echo "Running tccutil reset..."
    sudo tccutil reset ScreenCapture com.apple.Terminal

    echo ""
    echo "✅ Permission reset!"
    echo ""
    echo "Now:"
    echo "  1. Quit Terminal completely (Cmd+Q)"
    echo "  2. Reopen Terminal"
    echo "  3. Run: python3 check_screen_recording_permission.py"
    echo "  4. macOS will ask for Screen Recording permission"
    echo "  5. Click 'OK' or 'Allow'"
    echo ""

    read -p "Press ENTER to quit Terminal now..."
    osascript -e 'tell application "Terminal" to quit'
    exit 0
fi

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Option 2: Manual - Navigate to /usr/bin differently"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "In the file browser that's currently open:"
echo ""
echo "1. Look at the TOP of the window for the path dropdown"
echo "2. Click on the folder path area"
echo "3. You should see folder names like 'Macintosh HD'"
echo "4. Click on the path and select 'Go to Folder' from menu"
echo "5. Type: /usr/bin"
echo "6. Look for a file that shows 'python3' with NO file extension"
echo ""
echo "If you still can't see python3:"
echo "   - Make sure 'Show hidden files' is enabled"
echo "   - Try pressing: Cmd + Shift + . (period) to show hidden files"
echo ""

read -p "Press ENTER to continue..."

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Option 3: Just use Terminal permission (simpler)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Actually, Terminal permission SHOULD be enough since"
echo "Python runs inside Terminal."
echo ""
echo "Let's try this:"
echo ""
echo "1. Go back to System Preferences → Screen Recording"
echo "2. Make sure Terminal is checked: ☑️"
echo "3. UNCHECK Terminal (remove the checkmark)"
echo "4. Wait 2 seconds"
echo "5. CHECK Terminal again (put checkmark back)"
echo "6. Close System Preferences"
echo "7. Quit Terminal COMPLETELY (Cmd+Q)"
echo "8. Wait 5 seconds"
echo "9. Reopen Terminal"
echo "10. Run: python3 check_screen_recording_permission.py"
echo ""
echo "This 'un-check and re-check' trick sometimes refreshes the permission properly."
echo ""

read -p "Press ENTER to try this..."

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Option 4: Full system restart (nuclear option)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "If nothing else works, permissions sometimes need a full reboot:"
echo ""
echo "1. Make sure Terminal is checked in Screen Recording"
echo "2. Restart your Mac"
echo "3. After restart, open Terminal"
echo "4. cd to Ironcliw folder"
echo "5. Run: python3 check_screen_recording_permission.py"
echo ""

echo ""
echo "╔══════════════════════════════════════════════════════════════════╗"
echo "║  💡 Recommended: Try Option 1 (tccutil reset) first             ║"
echo "║     Then Option 3 (un-check/re-check) if that doesn't work      ║"
echo "╚══════════════════════════════════════════════════════════════════╝"
echo ""
